### ISSUE TITLE
post-link.sh is broken

### ISSUE THREAD

**Issue by ukoethe** [QuantForge/openexr-recipe#1]
`F >>` results in a "command not found" error

**Comment by wolfv** [comment]
I think we can actually remove it as it doesn't do anything useful

**Comment by gouarin** [comment]
I agree with @wolfv. We have the same kind of issue in `xeus-cling`.

**Comment by SylvainCorlay** [comment]
I removed the post-link script for `openexr` .

**Comment by SylvainCorlay** [comment]
> I agree with @wolfv. We have the same kind of issue in xeus-cling

What is the issue with xeus-cling? It does not have a post-link script right?

**Comment by gouarin** [comment]
@SylvainCorlay you're right. It is in gcc-7 recipe !!

**Comment by SylvainCorlay** [comment]
Closing as the post-link script for openexr was removed.
